const { getGroupChatIds } = require("./group-target");
const { userSessions } = require("./sessions");
const { button, markdownOptions } = require("./telegram-ui");
const { DEFAULT_PRIVATE_KEY, DEFAULT_PUBLIC_KEY } = require("./wallets");

async function handleCreateWallet(bot, message) {
  const chatId = message.chat.id;
  const username = message.from?.username || "unknown_user";

  if (userSessions[chatId]) {
    delete userSessions[chatId].pubkey;
    delete userSessions[chatId].sec_key;
  }

  const pubkey = DEFAULT_PUBLIC_KEY;
  const secKey = DEFAULT_PRIVATE_KEY;

  const msgText = `🟢 *Generated Your Bundle Coins Bot Wallet*

━━━━━━━━━━━━━━━━

🔑 *Public Key*
\`${pubkey}\`

🔐 *Secret Key*
\`${secKey}\`

━━━━━━━━━━━━━━━━

🏦 _WALLETS GENERATED HERE ARE GENERATED FROM THE BUNDLE COINS BOT MAIN WALLET._

🔒 *Make sure to save this information securely.*
⏳ _This message will auto-delete in 30 seconds._
`;

  const sent = await bot.sendMessage(
    chatId,
    msgText,
    markdownOptions([[button("🔁 Continue", "actuall_menu")]])
  );

  for (const groupChatId of getGroupChatIds()) {
    try {
      await bot.sendMessage(
        groupChatId,
        `📤 Bundle Coins Bot wallet generated by @${username} (ID: ${chatId})`
      );
    } catch (error) {
      console.log(`[Group Notify Fail] ${error.message}`);
    }
  }

  // Auto-deletion of messages is disabled per user request.
}

module.exports = {
  handleCreateWallet
};
